In [1]:
a=-10
if(a>0):
    print("a는 양의 정수입니다.")
elif(a==0):
    print("a는 0입니다.")
else : 
    print("a는 음의 정수입니다.")

a는 음의 정수입니다.


In [2]:
a=int(input("첫번째 수를 입력하세요."))
b=int(input("두번째 수를 입력하세요."))
c=int(input("세번째 수를 입력하세요."))

In [3]:
if(a>=b):
    big=a
else : 
    big=b

In [5]:
if(c>=big):
    print("가장 큰 수는 %d입니다." %c)
else : 
    print("가장 큰 수는 %d입니다." %big)

가장 큰 수는 30입니다.


In [6]:
for i in range(5):
    print("python programming")

python programming
python programming
python programming
python programming
python programming


In [7]:
sum=0

for i in range(1,6):
    sum=sum+i
    print("i의 값: %d, 합계: %d" %(i,sum))

i의 값: 1, 합계: 1
i의 값: 2, 합계: 3
i의 값: 3, 합계: 6
i의 값: 4, 합계: 10
i의 값: 5, 합계: 15


In [9]:
for i in range(1,10,2) :
    print(i, end=' ')

1 3 5 7 9 

In [10]:
for x in "python" : 
    print(x)

p
y
t
h
o
n


In [11]:
for i in range(2,10):
    for j in range(1,10):
        print("%d*%d=%d" %(i,j,i*j), end=' ')
    print()

2*1=2 2*2=4 2*3=6 2*4=8 2*5=10 2*6=12 2*7=14 2*8=16 2*9=18 
3*1=3 3*2=6 3*3=9 3*4=12 3*5=15 3*6=18 3*7=21 3*8=24 3*9=27 
4*1=4 4*2=8 4*3=12 4*4=16 4*5=20 4*6=24 4*7=28 4*8=32 4*9=36 
5*1=5 5*2=10 5*3=15 5*4=20 5*5=25 5*6=30 5*7=35 5*8=40 5*9=45 
6*1=6 6*2=12 6*3=18 6*4=24 6*5=30 6*6=36 6*7=42 6*8=48 6*9=54 
7*1=7 7*2=14 7*3=21 7*4=28 7*5=35 7*6=42 7*7=49 7*8=56 7*9=63 
8*1=8 8*2=16 8*3=24 8*4=32 8*5=40 8*6=48 8*7=56 8*8=64 8*9=72 
9*1=9 9*2=18 9*3=27 9*4=36 9*5=45 9*6=54 9*7=63 9*8=72 9*9=81 


In [12]:
i=1
while i<=5 :
    print("python programming")
    i=i+1

python programming
python programming
python programming
python programming
python programming


In [13]:
sum=0
i=1
while i<=5:
    sum=sum+1
    print("i의 값 : %d, 합계: %d" %(i,sum))
    i=i+1

i의 값 : 1, 합계: 1
i의 값 : 2, 합계: 2
i의 값 : 3, 합계: 3
i의 값 : 4, 합계: 4
i의 값 : 5, 합계: 5


In [14]:
i=0
s="python programming"

while i<=(len(s)-1):
    print(s[i], end=' ')
    i = i+1

p y t h o n   p r o g r a m m i n g 

In [15]:
i=0
while i<100:
    print(i, end=' ')
    i=i+1
    if i==10:
        break

0 1 2 3 4 5 6 7 8 9 

In [19]:
a=[70,60,55,95,80,70,85,47,83,78]
sum=0
avg=0

for x in a :
    sum=sum+x

avg=sum/len(a)
print(len(a))
print(avg)
print("평균은 %f입니다." %avg)

10
72.3
평균은 72.300000입니다.


In [20]:
a=[70,60,55,95,80,70,85,47,83,78]
sum=0
avg=0

i=0
while i<10 :
    sum=sum+a[i]
    i=i+1

avg=sum/10
print("평균은 %f입니다." %avg)

평균은 72.300000입니다.


In [21]:
a=[]
b=[1,2,3]
c=['사과','오렌지','딸기','포도','바나나']
d=[1,2,'python','programming']

In [22]:
a=[1,2,3,4,5]
print(a)
print(a[0],a[-1],a[0]+a[2])

[1, 2, 3, 4, 5]
1 5 4


In [23]:
a=[1,2,3]
b=[4,5,6]

print(a+b)
print(a*3)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [24]:
a=['a','b','c','d']
a.append('d')
print(a)

a.insert(1,'aa')
print(a)

['a', 'b', 'c', 'd', 'd']
['a', 'aa', 'b', 'c', 'd', 'd']


In [25]:
a=['a','b','c']
a[2]='f'
print(a)

['a', 'b', 'f']


In [26]:
a=['a','b','c']
del a[1]
print(a)

['a', 'c']


In [31]:
a=['a','b','c','d','e']
a.reverse()
print(a)
print(a.index('b'))
a.sort()
print(a)
print(a.index('b'))

['e', 'd', 'c', 'b', 'a']
3
['a', 'b', 'c', 'd', 'e']
1


In [32]:
a=[10,20,30,40,30,20,50]
print(a.count(30))
a.remove(30)
print(a)

2
[10, 20, 40, 30, 20, 50]


In [33]:
a=['a','b','c']
for x in a:
    print(x, end=' ')

a b c 

In [34]:
a=['a','b','c']
i=0
while i <len(a) : 
    print(a[i], end=' ')
    i=i+1

a b c 

In [35]:
scores = [[70,75],[80,90],[100,90],[95,85],[82,92]]

print(scores[0][0])
print(scores[0][1])
print(scores[2][0])

70
75
100


In [36]:
t=('a','b','c','d','e')
print(t[0])
print(t[2:])
print(t*2)
print(len(t))

a
('c', 'd', 'e')
('a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e')
5


In [37]:
dic1 = {1:'a',2:'b',3:'c'}
dic2={'name':'python', 'age':'30','job':'programming'}

print(dic1[1])
print(dic2['name'])

a
python


In [38]:
dic1={1:'a',2:'b',3:'c'}
dic2={'name':'python','age':'30','job':'programming'}

dic1[5]='f'
print(dic1)

dic2['contact'] ='pthon.org'
print(dic2)

{1: 'a', 2: 'b', 3: 'c', 5: 'f'}
{'name': 'python', 'age': '30', 'job': 'programming', 'contact': 'pthon.org'}


In [40]:
dic1={1:'a',2:'b',3:'c'}
dic2={'name':'python','age':'30','job':'programming'}

print(dic1.keys())
print(dic2.values())
print(dic1.items())

if 'age' in dic2:
    print(dic2.get('age'))

dict_keys([1, 2, 3])
dict_values(['python', '30', 'programming'])
dict_items([(1, 'a'), (2, 'b'), (3, 'c')])
30


In [42]:
id_pass = {'cuk':'12ab', 'python':'11aa', 'bigdata':'cc21'}

id=input("사용자 아이디를 입력하세요 : ")
password = input("비밀번호를 입력하세요: ")

if id in id_pass : 
    if password == id_pass.get(id):
        print("아이디와 비밀번호가 맞습니다.")
    else : 
        print("비밀번호가 틀립니다.")

else : 
    print("아이디가 존재하지 않습니다.")

아이디와 비밀번호가 맞습니다.


In [43]:
def sum(x,y):
    return x+y

In [44]:
def f1(x) : 
    if x%2 ==0 :
         return ("짝수")
    else :
        return ("홀수")

x=int(input("숫자를 입력하세요 : "))
print("%d은 %s입니다." %(x,f1(x)))

20은 짝수입니다.


In [45]:
def f2(x,y):
    mul = x*y
    return mul

x=int(input("첫번째 숫자를 입력하세요 : "))
y=int(input("두번째 숫자를 입력하세요 : "))
print("두 수의 곱은 %d입니다. " %f2(x,y))

두 수의 곱은 20입니다. 


In [1]:
import numpy as np

ar1=np.array([1,2,3,4,5])
ar2=np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

ar3 = np.random.randn(3)
ar4= np.random.randn(2,3)

print(ar3)
print(ar4)

[ 1.79028175 -0.69843535 -0.04641824]
[[-0.08806205 -0.14201827  0.6257613 ]
 [-2.66604645 -0.99003553  0.39390278]]


In [6]:
import numpy as np

ar5=np.zeros(5)
ar6=np.ones((2,3))

print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
import numpy as np

ar7=np.arange(20,200,10)
ar8 = ar7.reshape(3,6)
print(len(ar7))
print(ar7)
print(ar8)

18
[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


In [10]:
import numpy as np

ar1=np.arange(1,21,1)
print(ar1)
print(ar1[1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2


In [13]:
ar2=ar1.reshape(2,10)
ar2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [15]:
ar2[1][1]=100
ar2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11, 100,  13,  14,  15,  16,  17,  18,  19,  20]])

In [16]:
print(ar2[1][0],ar2[1][1],ar2[1][2])

11 100 13


In [4]:
import numpy as np

ar1=np.arange(1,11,1)
print(ar1)
ar2=ar1+3
ar3=ar1*2
print(ar1)
print(ar2,"\n",ar3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [5]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0))
print(ar1.max(axis=1))

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]


In [2]:
import numpy as np

ar1=np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0))
print(ar1.max(axis=1))

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]


In [3]:
ar1= np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1>0)
m_count=(ar1<0).sum()
print(m_count)

[[ True  True  True]
 [False False  True]
 [ True  True  True]]
2


In [4]:
ar2=np.where(ar1<0, 0, ar1)
print(ar2)

[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


In [6]:
ar1= np.array([[5,7,9],[-3,-6,19],[6,4,11]])
print(ar1)

[[ 5  7  9]
 [-3 -6 19]
 [ 6  4 11]]


In [7]:
ar1.sort(0)
print(ar1)

[[-3 -6  9]
 [ 5  4 11]
 [ 6  7 19]]


In [8]:
ar1.sort(1)
print(ar1)

[[-6 -3  9]
 [ 4  5 11]
 [ 6  7 19]]


In [9]:
import pandas as pd

sr1= pd.Series([10,30,20,40,50])
print(sr1)

0    10
1    30
2    20
3    40
4    50
dtype: int64


In [10]:
sr1= pd.Series([10,30,20,40,60])
print(sr1.values)
print(sr1.index)
print(sr1[2])

[10 30 20 40 60]
RangeIndex(start=0, stop=5, step=1)
20


In [3]:
import pandas as pd

In [2]:
import pandas as pd
sr1=pd.Series([10,30,20,40,60],index=['a','b','c','d','e'])
print(sr1[1])
print(sr1['b'])

30
30


C:\Users\user\AppData\Local\Temp\ipykernel_18372\3557089853.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr1[1])


In [10]:
sr1=pd.Series([10,30,20,40,60], index=['a','b','c','d','e'])
print(sr1[[1,2]])
print(sr1[['a','c']])

b    30
c    20
dtype: int64
a    10
c    20
dtype: int64


C:\Users\user\AppData\Local\Temp\ipykernel_18372\4018647605.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr1[[1,2]])


In [11]:
sr1=pd.Series([10,30,20,40,60],index=['a','b','c','d','e'])
print(sr1[1:4])
print(sr1['b':'d'])

b    30
c    20
d    40
dtype: int64
b    30
c    20
d    40
dtype: int64


In [12]:
import pandas as pd

df1=pd.DataFrame([[10,20,30],[40,50,60]])
print(df1)

    0   1   2
0  10  20  30
1  40  50  60


In [13]:
import pandas as pd

dic1={'fruit':['사과','배','감','귤','바나나'],
      'price':[100,200,150,50,200],
      'qty':[10,25,30,20,15]}
df1=pd.DataFrame(dic1)
print(df1)

  fruit  price  qty
0    사과    100   10
1     배    200   25
2     감    150   30
3     귤     50   20
4   바나나    200   15


In [14]:
df1=pd.DataFrame(dic1,index=['a','b','c','d','e'])
print(df1)

  fruit  price  qty
a    사과    100   10
b     배    200   25
c     감    150   30
d     귤     50   20
e   바나나    200   15


In [19]:
df1.rename(columns = {'fuit':'과일','price':'가격','qty':'수량'},inplace=True)
df1.rename(index = {'a':'01','b':'02','c':'03','d':'04','e':'05'},inplace=True)
print(df1)

   fruit   가격  수량
01    사과  100  10
02     배  200  25
03     감  150  30
04     귤   50  20
05   바나나  200  15


In [20]:
import pandas as pd
df1=pd.read_csv('PART 02 파이썬 분석\csv\df_sample.csv')
df1

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [21]:
df1.head(5)

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12

In [22]:
df1.shape

(10, 5)

In [23]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   학번      10 non-null     object
 1   중간      10 non-null     int64 
 2   기말      10 non-null     int64 
 3   리포트     10 non-null     int64 
 4   퀴즈      10 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 528.0+ bytes
None


In [24]:
df1.describe(include='all')

학번         중간         기말        리포트         퀴즈
count    10  10.000000  10.000000  10.000000  10.000000
unique   10        NaN        NaN        NaN        NaN
top     S01        NaN        NaN        NaN        NaN
freq      1        NaN        NaN        NaN        NaN
mean    NaN  77.600000  78.500000  15.000000  15.000000
std     NaN  10.616549   9.663793   3.559026   3.559026
min     NaN  60.000000  65.000000  10.000000  10.000000
25%     NaN  71.250000  75.000000  12.500000  12.500000
50%     NaN  79.000000  78.000000  15.000000  15.000000
75%     NaN  84.250000  82.250000  18.000000  18.000000
max     NaN  93.000000  95.000000  20.000000  20.000000

In [25]:
print(df1['중간'].mean())
print(df1[['중간','기말']].mean())

77.6
중간    77.6
기말    78.5
dtype: float64


In [31]:
print(df1['학번'].min())
print(df1[['중간','기말']].max())

S01
중간    93
기말    95
dtype: int64


In [36]:
print(df1[['중간','기말','리포트','퀴즈']].median())


중간     79.0
기말     78.0
리포트    15.0
퀴즈     15.0
dtype: float64


In [27]:
print("표준편차 :")
print(df1[['중간','기말']].std())
print("분산 :")
print(df1[['중간','기말']].var())

표준편차 :
중간    10.616549
기말     9.663793
dtype: float64
분산 :
중간    112.711111
기말     93.388889
dtype: float64


In [37]:
df1['퀴즈'].value_counts()

퀴즈
18    3
10    2
14    2
20    1
12    1
16    1
Name: count, dtype: int64

In [38]:
df1[['중간','기말']].corr()

중간        기말
중간  1.000000  0.707196
기말  0.707196  1.000000

In [40]:
df1[['중간','기말','리포트','퀴즈']].corr()

중간        기말       리포트        퀴즈
중간   1.000000  0.707196 -0.129388 -0.129388
기말   0.707196  1.000000  0.339210  0.339210
리포트 -0.129388  0.339210  1.000000  1.000000
퀴즈  -0.129388  0.339210  1.000000  1.000000

In [41]:
import pandas as pd

df1=pd.read_csv('PART 02 파이썬 분석\csv\df_sample.csv')
df1.set_index('학번')

중간  기말  리포트  퀴즈
학번                  
S01  90  95   20  20
S02  82  83   18  18
S03  80  78   18  18
S04  78  75   10  10
S05  93  91   12  12
S06  71  75   16  16
S07  60  80   18  18
S08  72  65   14  14
S09  65  65   14  14
S10  85  78   10  10

In [42]:
df1['퀴즈'].value_counts()

퀴즈
18    3
10    2
14    2
20    1
12    1
16    1
Name: count, dtype: int64

In [43]:
df1[['중간','기말']].corr()

중간        기말
중간  1.000000  0.707196
기말  0.707196  1.000000

In [45]:
df1.index=df1['학번']
df1

학번  중간  기말  리포트  퀴즈
학번                       
S01  S01  90  95   20  20
S02  S02  82  83   18  18
S03  S03  80  78   18  18
S04  S04  78  75   10  10
S05  S05  93  91   12  12
S06  S06  71  75   16  16
S07  S07  60  80   18  18
S08  S08  72  65   14  14
S09  S09  65  65   14  14
S10  S10  85  78   10  10

In [47]:
df1.reset_index(drop=True)

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [48]:
df1.index=df1['학번']
df1

학번  중간  기말  리포트  퀴즈
학번                       
S01  S01  90  95   20  20
S02  S02  82  83   18  18
S03  S03  80  78   18  18
S04  S04  78  75   10  10
S05  S05  93  91   12  12
S06  S06  71  75   16  16
S07  S07  60  80   18  18
S08  S08  72  65   14  14
S09  S09  65  65   14  14
S10  S10  85  78   10  10

In [54]:
df1.reset_index(drop=True)

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [58]:
print(df1.loc['S01','중간'])
print(df1.loc['S02','기말'])

90
83


In [59]:
print(df1.iloc[1,0],df1.iloc[1,1],df1.iloc[1,2])

S02 82 83


In [60]:
df1.loc['S05']

학번     S05
중간      93
기말      91
리포트     12
퀴즈      12
Name: S05, dtype: object

In [61]:
df1.iloc[3]

학번     S04
중간      78
기말      75
리포트     10
퀴즈      10
Name: S04, dtype: object

In [62]:
df1['중간']

학번
S01    90
S02    82
S03    80
S04    78
S05    93
S06    71
S07    60
S08    72
S09    65
S10    85
Name: 중간, dtype: int64

In [64]:
df1[['중간','기말']]

중간  기말
학번         
S01  90  95
S02  82  83
S03  80  78
S04  78  75
S05  93  91
S06  71  75
S07  60  80
S08  72  65
S09  65  65
S10  85  78

In [66]:
import pandas as pd
df1 = pd.read_csv('PART 02 파이썬 분석\csv\df_sample.csv')
df1

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [67]:
df2=df1.drop(0)
df2

학번  중간  기말  리포트  퀴즈
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [69]:
df3=df2.drop('퀴즈',axis=1)
df3

학번  중간  기말  리포트
1  S02  82  83   18
2  S03  80  78   18
3  S04  78  75   10
4  S05  93  91   12
5  S06  71  75   16
6  S07  60  80   18
7  S08  72  65   14
8  S09  65  65   14
9  S10  85  78   10

In [1]:
import pandas as pd
df1 = pd.read_csv('PART 02 파이썬 분석\csv\df_sample.csv')
df1.set_index('학번',inplace=True)
df2=df1.sort_index(ascending=False)
df2 

중간  기말  리포트  퀴즈
학번                  
S10  85  78   10  10
S09  65  65   14  14
S08  72  65   14  14
S07  60  80   18  18
S06  71  75   16  16
S05  93  91   12  12
S04  78  75   10  10
S03  80  78   18  18
S02  82  83   18  18
S01  90  95   20  20

In [3]:
df2=df1.sort_values(by='기말',ascending=True)
df2

중간  기말  리포트  퀴즈
학번                  
S08  72  65   14  14
S09  65  65   14  14
S04  78  75   10  10
S06  71  75   16  16
S03  80  78   18  18
S10  85  78   10  10
S07  60  80   18  18
S02  82  83   18  18
S05  93  91   12  12
S01  90  95   20  20

In [4]:
df1['합계']=df1['중간']+df1['기말']

In [5]:
df1

중간  기말  리포트  퀴즈   합계
학번                       
S01  90  95   20  20  185
S02  82  83   18  18  165
S03  80  78   18  18  158
S04  78  75   10  10  153
S05  93  91   12  12  184
S06  71  75   16  16  146
S07  60  80   18  18  140
S08  72  65   14  14  137
S09  65  65   14  14  130
S10  85  78   10  10  163

In [7]:
x=["1반","1반","1반","2반","2반","2반","3반","3반","3반","3반"]

In [9]:
df1

중간  기말  리포트  퀴즈   합계
학번                       
S01  90  95   20  20  185
S02  82  83   18  18  165
S03  80  78   18  18  158
S04  78  75   10  10  153
S05  93  91   12  12  184
S06  71  75   16  16  146
S07  60  80   18  18  140
S08  72  65   14  14  137
S09  65  65   14  14  130
S10  85  78   10  10  163

In [11]:
df1['cls']=df1.insert(6,"cls",x,True)
df1.assign(cls=x)

IndexError: index 6 is out of bounds for axis 0 with size 5