In [1]:
a=-10
if(a>0):
    print("a는 양의 정수입니다.")
elif(a==0):
    print("a는 0입니다.")
else : 
    print("a는 음의 정수입니다.")

a는 음의 정수입니다.


In [2]:
a=int(input("첫번째 수를 입력하세요."))
b=int(input("두번째 수를 입력하세요."))
c=int(input("세번째 수를 입력하세요."))

In [3]:
if(a>=b):
    big=a
else : 
    big=b

In [4]:
if(c>=big):
    print("가장 큰 수는 %d입니다." %c)
else : 
    print("가장 큰 수는 %d입니다." %big)

가장 큰 수는 30입니다.


In [5]:
for i in range(5):
    print("python programming")

python programming
python programming
python programming
python programming
python programming


In [6]:
sum=0

for i in range(1,6):
    sum=sum+i
    print("i의 값: %d, 합계: %d" %(i,sum))

i의 값: 1, 합계: 1
i의 값: 2, 합계: 3
i의 값: 3, 합계: 6
i의 값: 4, 합계: 10
i의 값: 5, 합계: 15


In [7]:
for i in range(1,10,2) :
    print(i, end=' ')

1 3 5 7 9 

In [8]:
for x in "python" : 
    print(x)

p
y
t
h
o
n


In [9]:
for i in range(2,10):
    for j in range(1,10):
        print("%d*%d=%d" %(i,j,i*j), end=' ')
    print()

2*1=2 2*2=4 2*3=6 2*4=8 2*5=10 2*6=12 2*7=14 2*8=16 2*9=18 
3*1=3 3*2=6 3*3=9 3*4=12 3*5=15 3*6=18 3*7=21 3*8=24 3*9=27 
4*1=4 4*2=8 4*3=12 4*4=16 4*5=20 4*6=24 4*7=28 4*8=32 4*9=36 
5*1=5 5*2=10 5*3=15 5*4=20 5*5=25 5*6=30 5*7=35 5*8=40 5*9=45 
6*1=6 6*2=12 6*3=18 6*4=24 6*5=30 6*6=36 6*7=42 6*8=48 6*9=54 
7*1=7 7*2=14 7*3=21 7*4=28 7*5=35 7*6=42 7*7=49 7*8=56 7*9=63 
8*1=8 8*2=16 8*3=24 8*4=32 8*5=40 8*6=48 8*7=56 8*8=64 8*9=72 
9*1=9 9*2=18 9*3=27 9*4=36 9*5=45 9*6=54 9*7=63 9*8=72 9*9=81 


In [10]:
i=1
while i<=5 :
    print("python programming")
    i=i+1

python programming
python programming
python programming
python programming
python programming


In [11]:
sum=0
i=1
while i<=5:
    sum=sum+1
    print("i의 값 : %d, 합계: %d" %(i,sum))
    i=i+1

i의 값 : 1, 합계: 1
i의 값 : 2, 합계: 2
i의 값 : 3, 합계: 3
i의 값 : 4, 합계: 4
i의 값 : 5, 합계: 5


In [12]:
i=0
s="python programming"

while i<=(len(s)-1):
    print(s[i], end=' ')
    i = i+1

p y t h o n   p r o g r a m m i n g 

In [13]:
i=0
while i<100:
    print(i, end=' ')
    i=i+1
    if i==10:
        break

0 1 2 3 4 5 6 7 8 9 

In [14]:
a=[70,60,55,95,80,70,85,47,83,78]
sum=0
avg=0

for x in a :
    sum=sum+x

avg=sum/len(a)
print(len(a))
print(avg)
print("평균은 %f입니다." %avg)

10
72.3
평균은 72.300000입니다.


In [15]:
a=[70,60,55,95,80,70,85,47,83,78]
sum=0
avg=0

i=0
while i<10 :
    sum=sum+a[i]
    i=i+1

avg=sum/10
print("평균은 %f입니다." %avg)

평균은 72.300000입니다.


In [16]:
a=[]
b=[1,2,3]
c=['사과','오렌지','딸기','포도','바나나']
d=[1,2,'python','programming']

In [17]:
a=[1,2,3,4,5]
print(a)
print(a[0],a[-1],a[0]+a[2])

[1, 2, 3, 4, 5]
1 5 4


In [18]:
a=[1,2,3]
b=[4,5,6]

print(a+b)
print(a*3)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [19]:
a=['a','b','c','d']
a.append('d')
print(a)

a.insert(1,'aa')
print(a)

['a', 'b', 'c', 'd', 'd']
['a', 'aa', 'b', 'c', 'd', 'd']


In [20]:
a=['a','b','c']
a[2]='f'
print(a)

['a', 'b', 'f']


In [21]:
a=['a','b','c']
del a[1]
print(a)

['a', 'c']


In [22]:
a=['a','b','c','d','e']
a.reverse()
print(a)
print(a.index('b'))
a.sort()
print(a)
print(a.index('b'))

['e', 'd', 'c', 'b', 'a']
3
['a', 'b', 'c', 'd', 'e']
1


In [23]:
a=[10,20,30,40,30,20,50]
print(a.count(30))
a.remove(30)
print(a)

2
[10, 20, 40, 30, 20, 50]


In [24]:
a=['a','b','c']
for x in a:
    print(x, end=' ')

a b c 

In [25]:
a=['a','b','c']
i=0
while i <len(a) : 
    print(a[i], end=' ')
    i=i+1

a b c 

In [26]:
scores = [[70,75],[80,90],[100,90],[95,85],[82,92]]

print(scores[0][0])
print(scores[0][1])
print(scores[2][0])

70
75
100


In [27]:
t=('a','b','c','d','e')
print(t[0])
print(t[2:])
print(t*2)
print(len(t))

a
('c', 'd', 'e')
('a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e')
5


In [28]:
dic1 = {1:'a',2:'b',3:'c'}
dic2={'name':'python', 'age':'30','job':'programming'}

print(dic1[1])
print(dic2['name'])

a
python


In [29]:
dic1={1:'a',2:'b',3:'c'}
dic2={'name':'python','age':'30','job':'programming'}

dic1[5]='f'
print(dic1)

dic2['contact'] ='pthon.org'
print(dic2)

{1: 'a', 2: 'b', 3: 'c', 5: 'f'}
{'name': 'python', 'age': '30', 'job': 'programming', 'contact': 'pthon.org'}


In [30]:
dic1={1:'a',2:'b',3:'c'}
dic2={'name':'python','age':'30','job':'programming'}

print(dic1.keys())
print(dic2.values())
print(dic1.items())

if 'age' in dic2:
    print(dic2.get('age'))

dict_keys([1, 2, 3])
dict_values(['python', '30', 'programming'])
dict_items([(1, 'a'), (2, 'b'), (3, 'c')])
30


In [31]:
id_pass = {'cuk':'12ab', 'python':'11aa', 'bigdata':'cc21'}

id=input("사용자 아이디를 입력하세요 : ")
password = input("비밀번호를 입력하세요: ")

if id in id_pass : 
    if password == id_pass.get(id):
        print("아이디와 비밀번호가 맞습니다.")
    else : 
        print("비밀번호가 틀립니다.")

else : 
    print("아이디가 존재하지 않습니다.")

아이디가 존재하지 않습니다.


In [32]:
def sum(x,y):
    return x+y

In [33]:
def f1(x) : 
    if x%2 ==0 :
         return ("짝수")
    else :
        return ("홀수")

x=int(input("숫자를 입력하세요 : "))
print("%d은 %s입니다." %(x,f1(x)))

10은 짝수입니다.


In [34]:
def f2(x,y):
    mul = x*y
    return mul

x=int(input("첫번째 숫자를 입력하세요 : "))
y=int(input("두번째 숫자를 입력하세요 : "))
print("두 수의 곱은 %d입니다. " %f2(x,y))

두 수의 곱은 600입니다. 


In [35]:
import numpy as np

ar1=np.array([1,2,3,4,5])
ar2=np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [36]:
import numpy as np

ar3 = np.random.randn(3)
ar4= np.random.randn(2,3)

print(ar3)
print(ar4)

[0.36813484 1.3030537  0.7439823 ]
[[ 0.48894726  0.17942614  0.4477894 ]
 [ 0.40061904 -0.48308728  0.30432931]]


In [37]:
import numpy as np

ar5=np.zeros(5)
ar6=np.ones((2,3))

print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
import numpy as np

ar7=np.arange(20,200,10)
ar8 = ar7.reshape(3,6)
print(len(ar7))
print(ar7)
print(ar8)

18
[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


In [39]:
import numpy as np

ar1=np.arange(1,21,1)
print(ar1)
print(ar1[1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2


In [40]:
ar2=ar1.reshape(2,10)
ar2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [41]:
ar2[1][1]=100
ar2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11, 100,  13,  14,  15,  16,  17,  18,  19,  20]])

In [42]:
print(ar2[1][0],ar2[1][1],ar2[1][2])

11 100 13


In [43]:
import numpy as np

ar1=np.arange(1,11,1)
print(ar1)
ar2=ar1+3
ar3=ar1*2
print(ar1)
print(ar2,"\n",ar3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [44]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0))
print(ar1.max(axis=1))

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]


In [45]:
import numpy as np

ar1=np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0))
print(ar1.max(axis=1))

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]


In [46]:
ar1= np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1>0)
m_count=(ar1<0).sum()
print(m_count)

[[ True  True  True]
 [False False  True]
 [ True  True  True]]
2


In [47]:
ar2=np.where(ar1<0, 0, ar1)
print(ar2)

[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


In [48]:
ar1= np.array([[5,7,9],[-3,-6,19],[6,4,11]])
print(ar1)

[[ 5  7  9]
 [-3 -6 19]
 [ 6  4 11]]


In [49]:
ar1.sort(0)
print(ar1)

[[-3 -6  9]
 [ 5  4 11]
 [ 6  7 19]]


In [50]:
ar1.sort(1)
print(ar1)

[[-6 -3  9]
 [ 4  5 11]
 [ 6  7 19]]


In [51]:
import pandas as pd

sr1= pd.Series([10,30,20,40,50])
print(sr1)

0    10
1    30
2    20
3    40
4    50
dtype: int64


In [52]:
sr1= pd.Series([10,30,20,40,60])
print(sr1.values)
print(sr1.index)
print(sr1[2])

[10 30 20 40 60]
RangeIndex(start=0, stop=5, step=1)
20


In [53]:
import pandas as pd

In [54]:
import pandas as pd
sr1=pd.Series([10,30,20,40,60],index=['a','b','c','d','e'])
print(sr1[1])
print(sr1['b'])

30
30


C:\Users\user\AppData\Local\Temp\ipykernel_14696\3557089853.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr1[1])


In [55]:
sr1=pd.Series([10,30,20,40,60], index=['a','b','c','d','e'])
print(sr1[[1,2]])
print(sr1[['a','c']])

b    30
c    20
dtype: int64
a    10
c    20
dtype: int64


C:\Users\user\AppData\Local\Temp\ipykernel_14696\4018647605.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr1[[1,2]])


In [56]:
sr1=pd.Series([10,30,20,40,60],index=['a','b','c','d','e'])
print(sr1[1:4])
print(sr1['b':'d'])

b    30
c    20
d    40
dtype: int64
b    30
c    20
d    40
dtype: int64


In [57]:
import pandas as pd

df1=pd.DataFrame([[10,20,30],[40,50,60]])
print(df1)

    0   1   2
0  10  20  30
1  40  50  60


In [58]:
import pandas as pd

dic1={'fruit':['사과','배','감','귤','바나나'],
      'price':[100,200,150,50,200],
      'qty':[10,25,30,20,15]}
df1=pd.DataFrame(dic1)
print(df1)

  fruit  price  qty
0    사과    100   10
1     배    200   25
2     감    150   30
3     귤     50   20
4   바나나    200   15


In [59]:
df1=pd.DataFrame(dic1,index=['a','b','c','d','e'])
print(df1)

  fruit  price  qty
a    사과    100   10
b     배    200   25
c     감    150   30
d     귤     50   20
e   바나나    200   15


In [60]:
df1.rename(columns = {'fuit':'과일','price':'가격','qty':'수량'},inplace=True)
df1.rename(index = {'a':'01','b':'02','c':'03','d':'04','e':'05'},inplace=True)
print(df1)

   fruit   가격  수량
01    사과  100  10
02     배  200  25
03     감  150  30
04     귤   50  20
05   바나나  200  15


In [61]:
import pandas as pd
df1=pd.read_csv('PART 02 파이썬 분석\csv\df_sample.csv')
df1

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [62]:
df1.head(5)

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12

In [63]:
df1.shape

(10, 5)

In [64]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   학번      10 non-null     object
 1   중간      10 non-null     int64 
 2   기말      10 non-null     int64 
 3   리포트     10 non-null     int64 
 4   퀴즈      10 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 528.0+ bytes
None


In [65]:
df1.describe(include='all')

학번         중간         기말        리포트         퀴즈
count    10  10.000000  10.000000  10.000000  10.000000
unique   10        NaN        NaN        NaN        NaN
top     S01        NaN        NaN        NaN        NaN
freq      1        NaN        NaN        NaN        NaN
mean    NaN  77.600000  78.500000  15.000000  15.000000
std     NaN  10.616549   9.663793   3.559026   3.559026
min     NaN  60.000000  65.000000  10.000000  10.000000
25%     NaN  71.250000  75.000000  12.500000  12.500000
50%     NaN  79.000000  78.000000  15.000000  15.000000
75%     NaN  84.250000  82.250000  18.000000  18.000000
max     NaN  93.000000  95.000000  20.000000  20.000000

In [66]:
print(df1['중간'].mean())
print(df1[['중간','기말']].mean())

77.6
중간    77.6
기말    78.5
dtype: float64


In [67]:
print(df1['학번'].min())
print(df1[['중간','기말']].max())

S01
중간    93
기말    95
dtype: int64


In [68]:
print(df1[['중간','기말','리포트','퀴즈']].median())


중간     79.0
기말     78.0
리포트    15.0
퀴즈     15.0
dtype: float64


In [69]:
print("표준편차 :")
print(df1[['중간','기말']].std())
print("분산 :")
print(df1[['중간','기말']].var())

표준편차 :
중간    10.616549
기말     9.663793
dtype: float64
분산 :
중간    112.711111
기말     93.388889
dtype: float64


In [70]:
df1['퀴즈'].value_counts()

퀴즈
18    3
10    2
14    2
20    1
12    1
16    1
Name: count, dtype: int64

In [71]:
df1[['중간','기말']].corr()

중간        기말
중간  1.000000  0.707196
기말  0.707196  1.000000

In [72]:
df1[['중간','기말','리포트','퀴즈']].corr()

중간        기말       리포트        퀴즈
중간   1.000000  0.707196 -0.129388 -0.129388
기말   0.707196  1.000000  0.339210  0.339210
리포트 -0.129388  0.339210  1.000000  1.000000
퀴즈  -0.129388  0.339210  1.000000  1.000000

In [73]:
import pandas as pd

df1=pd.read_csv('PART 02 파이썬 분석\csv\df_sample.csv')
df1.set_index('학번')

중간  기말  리포트  퀴즈
학번                  
S01  90  95   20  20
S02  82  83   18  18
S03  80  78   18  18
S04  78  75   10  10
S05  93  91   12  12
S06  71  75   16  16
S07  60  80   18  18
S08  72  65   14  14
S09  65  65   14  14
S10  85  78   10  10

In [74]:
df1['퀴즈'].value_counts()

퀴즈
18    3
10    2
14    2
20    1
12    1
16    1
Name: count, dtype: int64

In [75]:
df1[['중간','기말']].corr()

중간        기말
중간  1.000000  0.707196
기말  0.707196  1.000000

In [76]:
df1.index=df1['학번']
df1

학번  중간  기말  리포트  퀴즈
학번                       
S01  S01  90  95   20  20
S02  S02  82  83   18  18
S03  S03  80  78   18  18
S04  S04  78  75   10  10
S05  S05  93  91   12  12
S06  S06  71  75   16  16
S07  S07  60  80   18  18
S08  S08  72  65   14  14
S09  S09  65  65   14  14
S10  S10  85  78   10  10

In [77]:
df1.reset_index(drop=True)

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [78]:
df1.index=df1['학번']
df1

학번  중간  기말  리포트  퀴즈
학번                       
S01  S01  90  95   20  20
S02  S02  82  83   18  18
S03  S03  80  78   18  18
S04  S04  78  75   10  10
S05  S05  93  91   12  12
S06  S06  71  75   16  16
S07  S07  60  80   18  18
S08  S08  72  65   14  14
S09  S09  65  65   14  14
S10  S10  85  78   10  10

In [79]:
df1.reset_index(drop=True)

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [80]:
print(df1.loc['S01','중간'])
print(df1.loc['S02','기말'])

90
83


In [81]:
print(df1.iloc[1,0],df1.iloc[1,1],df1.iloc[1,2])

S02 82 83


In [82]:
df1.loc['S05']

학번     S05
중간      93
기말      91
리포트     12
퀴즈      12
Name: S05, dtype: object

In [83]:
df1.iloc[3]

학번     S04
중간      78
기말      75
리포트     10
퀴즈      10
Name: S04, dtype: object

In [84]:
df1['중간']

학번
S01    90
S02    82
S03    80
S04    78
S05    93
S06    71
S07    60
S08    72
S09    65
S10    85
Name: 중간, dtype: int64

In [85]:
df1[['중간','기말']]

중간  기말
학번         
S01  90  95
S02  82  83
S03  80  78
S04  78  75
S05  93  91
S06  71  75
S07  60  80
S08  72  65
S09  65  65
S10  85  78

In [86]:
import pandas as pd
df1 = pd.read_csv('PART 02 파이썬 분석\csv\df_sample.csv')
df1

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [87]:
df2=df1.drop(0)
df2

학번  중간  기말  리포트  퀴즈
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [88]:
df3=df2.drop('퀴즈',axis=1)
df3

학번  중간  기말  리포트
1  S02  82  83   18
2  S03  80  78   18
3  S04  78  75   10
4  S05  93  91   12
5  S06  71  75   16
6  S07  60  80   18
7  S08  72  65   14
8  S09  65  65   14
9  S10  85  78   10

In [117]:
import pandas as pd
df1 = pd.read_csv('PART 02 파이썬 분석\csv\df_sample.csv')
df1.set_index('학번',inplace=True)
df2=df1.sort_index(ascending=False)
df2 

중간  기말  리포트  퀴즈
학번                  
S10  85  78   10  10
S09  65  65   14  14
S08  72  65   14  14
S07  60  80   18  18
S06  71  75   16  16
S05  93  91   12  12
S04  78  75   10  10
S03  80  78   18  18
S02  82  83   18  18
S01  90  95   20  20

In [90]:
df2=df1.sort_values(by='기말',ascending=True)
df2

중간  기말  리포트  퀴즈
학번                  
S08  72  65   14  14
S09  65  65   14  14
S04  78  75   10  10
S06  71  75   16  16
S03  80  78   18  18
S10  85  78   10  10
S07  60  80   18  18
S02  82  83   18  18
S05  93  91   12  12
S01  90  95   20  20

In [91]:
df1['합계']=df1['중간']+df1['기말']

In [92]:
df1

중간  기말  리포트  퀴즈   합계
학번                       
S01  90  95   20  20  185
S02  82  83   18  18  165
S03  80  78   18  18  158
S04  78  75   10  10  153
S05  93  91   12  12  184
S06  71  75   16  16  146
S07  60  80   18  18  140
S08  72  65   14  14  137
S09  65  65   14  14  130
S10  85  78   10  10  163

In [93]:
x=["1반","1반","1반","2반","2반","2반","3반","3반","3반","3반"]

In [94]:
df1

중간  기말  리포트  퀴즈   합계
학번                       
S01  90  95   20  20  185
S02  82  83   18  18  165
S03  80  78   18  18  158
S04  78  75   10  10  153
S05  93  91   12  12  184
S06  71  75   16  16  146
S07  60  80   18  18  140
S08  72  65   14  14  137
S09  65  65   14  14  130
S10  85  78   10  10  163

In [99]:
df1["cls"]=x
df1.insert(6,"cls",x,True)
df1

중간  기말  리포트  퀴즈   합계 cls cls cls cls cls
학번                                           
S01  90  95   20  20  185  1반  1반  1반  1반  1반
S02  82  83   18  18  165  1반  1반  1반  1반  1반
S03  80  78   18  18  158  1반  1반  1반  1반  1반
S04  78  75   10  10  153  2반  2반  2반  2반  2반
S05  93  91   12  12  184  2반  2반  2반  2반  2반
S06  71  75   16  16  146  2반  2반  2반  2반  2반
S07  60  80   18  18  140  3반  3반  3반  3반  3반
S08  72  65   14  14  137  3반  3반  3반  3반  3반
S09  65  65   14  14  130  3반  3반  3반  3반  3반
S10  85  78   10  10  163  3반  3반  3반  3반  3반

In [116]:
df1.assign(cls=x)
df1.loc[:,"cls"]=x

In [102]:
import numpy as np

mid_avg = np.mean(df1["중간"])
mid_std = np.std(df1["중간"])

df1["중간_Z점수"]=(df1["중간"]-mid_avg)/mid_std
df1.head()

중간  기말  리포트  퀴즈   합계 cls cls cls cls cls    중간_Z점수
학번                                                     
S01  90  95   20  20  185  1반  1반  1반  1반  1반  1.231167
S02  82  83   18  18  165  1반  1반  1반  1반  1반  0.436866
S03  80  78   18  18  158  1반  1반  1반  1반  1반  0.238290
S04  78  75   10  10  153  2반  2반  2반  2반  2반  0.039715
S05  93  91   12  12  184  2반  2반  2반  2반  2반  1.529030

In [105]:
fin_min=np.min(df1["기말"])
fin_max=np.max(df1["기말"])

df1["기말_정규화"]=(df1["기말"]-fin_min)/(fin_max-fin_min)
df1.head()

중간  기말  리포트  퀴즈   합계 cls cls cls cls cls    중간_Z점수    기말_정규화
학번                                                               
S01  90  95   20  20  185  1반  1반  1반  1반  1반  1.231167  1.000000
S02  82  83   18  18  165  1반  1반  1반  1반  1반  0.436866  0.600000
S03  80  78   18  18  158  1반  1반  1반  1반  1반  0.238290  0.433333
S04  78  75   10  10  153  2반  2반  2반  2반  2반  0.039715  0.333333
S05  93  91   12  12  184  2반  2반  2반  2반  2반  1.529030  0.866667

In [112]:
df1=df1.loc[:,~df1.T.duplicated()]   #중복된 열 제거
df1

중간  기말  리포트   합계 cls    중간_Z점수    기말_정규화
학번                                           
S01  90  95   20  185  1반  1.231167  1.000000
S02  82  83   18  165  1반  0.436866  0.600000
S03  80  78   18  158  1반  0.238290  0.433333
S04  78  75   10  153  2반  0.039715  0.333333
S05  93  91   12  184  2반  1.529030  0.866667
S06  71  75   16  146  2반 -0.655299  0.333333
S07  60  80   18  140  3반 -1.747463  0.500000
S08  72  65   14  137  3반 -0.556011  0.000000
S09  65  65   14  130  3반 -1.251025  0.000000
S10  85  78   10  163  3반  0.734729  0.433333

In [113]:
df1_cls_grp=df1.groupby(df1["cls"])
df1_cls_grp.mean()

중간         기말        리포트          합계    중간_Z점수    기말_정규화
cls                                                                 
1반   84.000000  85.333333  18.666667  169.333333  0.635441  0.677778
2반   80.666667  80.333333  12.666667  161.000000  0.304482  0.511111
3반   70.500000  72.000000  14.000000  142.500000 -0.704943  0.233333

In [114]:
df1['중간'].groupby(df1["cls"]).count()

cls
1반    3
2반    3
3반    4
Name: 중간, dtype: int64

In [118]:
df1["퀴즈"].apply(np.sqrt)

학번
S01    4.472136
S02    4.242641
S03    4.242641
S04    3.162278
S05    3.464102
S06    4.000000
S07    4.242641
S08    3.741657
S09    3.741657
S10    3.162278
Name: 퀴즈, dtype: float64

In [119]:
x=[14,15,13,14,None,None,19,11,12,18]
df1["토론"]=x

df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, S01 to S10
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   중간      10 non-null     int64  
 1   기말      10 non-null     int64  
 2   리포트     10 non-null     int64  
 3   퀴즈      10 non-null     int64  
 4   토론      8 non-null      float64
dtypes: float64(1), int64(4)
memory usage: 780.0+ bytes


In [122]:
df1.isnull()

중간     기말    리포트     퀴즈     토론
학번                                    
S01  False  False  False  False  False
S02  False  False  False  False  False
S03  False  False  False  False  False
S04  False  False  False  False  False
S05  False  False  False  False   True
S06  False  False  False  False   True
S07  False  False  False  False  False
S08  False  False  False  False  False
S09  False  False  False  False  False
S10  False  False  False  False  False

In [124]:
df1.notnull()

중간    기말   리포트    퀴즈     토론
학번                                
S01  True  True  True  True   True
S02  True  True  True  True   True
S03  True  True  True  True   True
S04  True  True  True  True   True
S05  True  True  True  True  False
S06  True  True  True  True  False
S07  True  True  True  True   True
S08  True  True  True  True   True
S09  True  True  True  True   True
S10  True  True  True  True   True

In [125]:
df1_new=df1.dropna(axis=0)

In [127]:
df1_new.isnull()

중간     기말    리포트     퀴즈     토론
학번                                    
S01  False  False  False  False  False
S02  False  False  False  False  False
S03  False  False  False  False  False
S04  False  False  False  False  False
S07  False  False  False  False  False
S08  False  False  False  False  False
S09  False  False  False  False  False
S10  False  False  False  False  False

In [129]:
df_new=df1["토론"].dropna()

In [130]:
d_mean=df1["토론"].mean()
df1["토론"].fillna(d_mean,inplace=True)
df1

C:\Users\user\AppData\Local\Temp\ipykernel_14696\199277687.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["토론"].fillna(d_mean,inplace=True)


중간  기말  리포트  퀴즈    토론
학번                        
S01  90  95   20  20  14.0
S02  82  83   18  18  15.0
S03  80  78   18  18  13.0
S04  78  75   10  10  14.0
S05  93  91   12  12  14.5
S06  71  75   16  16  14.5
S07  60  80   18  18  19.0
S08  72  65   14  14  11.0
S09  65  65   14  14  12.0
S10  85  78   10  10  18.0

In [131]:
df_1QR=df1["기말"].quantile(0.25)
df_3QR=df1["기말"].quantile(0.75)
df_IQR=df_3QR-df_1QR
print(df_1QR)
print(df_3QR)
print(df_IQR)

75.0
82.25
7.25
