# 파이썬 데이터 사이언스 핸드북_Pandas

In [1]:
import pandas
pandas.__version__

'2.2.2'

In [4]:
import pandas as pd
import numpy as np

# Pandas Series 객체

In [6]:
data=pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
data[1]

0.5

In [10]:
data[1:3]

1    0.50
2    0.75
dtype: float64

# Series : 일반화된 Numpy 배열

In [11]:
data=pd.Series([0.25,0.5,0.75,1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [12]:
data['b']

0.5

In [13]:
data=pd.Series([0.25,0.5,0.75,1.0],
index=[2,5,3,7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [14]:
data[5]

0.5

In [15]:
data[1:3]

5    0.50
3    0.75
dtype: float64

# Series:특수한 딕셔너리

In [18]:
population_dict = {'California':38332521,
                   'Texas':26448193,
                   'New York':19552860,
                   'Florida':12882135,
                   'Illinois':12882135}
population=pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19552860
Florida       12882135
Illinois      12882135
dtype: int64

In [19]:
population['California']

38332521

In [20]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19552860
Florida       12882135
Illinois      12882135
dtype: int64

# Series 객체 구성하기

In [25]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [26]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [27]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [28]:
pd.Series({2:'a',1:'b',3:'c'},index=[3,2])

3    c
2    a
dtype: object

# Pandas DataFrame  객체

In [36]:
# DataFrame : 일반화된 Numpy 배열

area_dict={'California':4423967,'Texas':695662,'New York':141297,'Florida':170312,'Illinois':149995}
area=pd.Series(area_dict)
area

California    4423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
dtype: int64

In [37]:
states = pd.DataFrame({'population':population, 'area':area})
states

population     area
California    38332521  4423967
Texas         26448193   695662
New York      19552860   141297
Florida       12882135   170312
Illinois      12882135   149995

In [38]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [39]:
states.columns

Index(['population', 'area'], dtype='object')

# DataFrame : 특수한 딕셔너리

In [40]:
states['area']

California    4423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [41]:
pd.DataFrame(population,columns=['population'])

population
California    38332521
Texas         26448193
New York      19552860
Florida       12882135
Illinois      12882135

In [42]:
data=[{'a':i,'b':2*i}
    for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [43]:
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [44]:
pd.DataFrame({'population':population,'area':area})

population     area
California    38332521  4423967
Texas         26448193   695662
New York      19552860   141297
Florida       12882135   170312
Illinois      12882135   149995

In [45]:
pd.DataFrame(np.random.rand(3,2),
             columns=['foo','bar'],
             index=['a','b','c'])

foo       bar
a  0.489465  0.966066
b  0.044569  0.713566
c  0.337624  0.439121

In [47]:
A=np.zeros(3,dtype=[('A','i8'),('B','f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [48]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

# Pandas Index 객체

In [49]:
ind =pd.Index([2,3,5,7,11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [50]:
ind[1]

3

In [51]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [52]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64


In [53]:
ind[1]=0

TypeError: Index does not support mutable operations

In [54]:
indA=pd.Index([1,3,5,7,9])
indB=pd.Index([2,3,5,7,11])

In [56]:
indA & indB

Index([0, 3, 5, 7, 9], dtype='int64')

In [57]:
indA | indB

Index([3, 3, 5, 7, 11], dtype='int64')

In [58]:
indA ^ indB

Index([3, 0, 0, 0, 2], dtype='int64')

# 데이터 인덱싱과 선택

In [63]:
# Series : 딕셔너리

import pandas as pd
data=pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [64]:
data['b']

0.5

In [65]:
'a' in data

True

In [66]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [67]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [69]:
data['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

# Series : 1차원 배열
-명시적 인덱스 (즉, data['a':'c'])로 슬라이싱 할때는 최종 인덱스가 슬라이스에 포함되지만, \
 암묵적 인덱스(즉, data[0:2])로 슬라이싱하면 최종인덱스가 그 슬라이스에서 제외된다.

In [70]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [71]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [72]:
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [73]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

In [74]:
data=pd.Series(['a','b','c'],index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [75]:
data[1]

'a'

In [76]:
data[1:3]

3    b
5    c
dtype: object

# 인덱서 : loc와 iloc

In [80]:
data.loc[1]

'a'

In [81]:
data.loc[1:3]

1    a
3    b
dtype: object

In [82]:
data.iloc[1]

'b'

In [83]:
data.iloc[1:3]

3    b
5    c
dtype: object

# DataFrame : 딕셔너리

In [86]:
area = pd.Series({'California':423967, 'Texas':695662, 'Florida':170312, 'New York':141297, 'Pennsylvania':119280})
pop = pd.Series({'California':39538223, 'Texas':29145505, 'Florida':21538187, 'New York':20201249, 'Pennsylvania':13002700})
data = pd.DataFrame({'area':area,'pop':pop})
data

area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [87]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [88]:
data.area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [89]:
data.pop is data['pop']

False

In [91]:
data['density']=data['pop']/data['area']
data

area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

In [92]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.19280000e+05, 1.30027000e+07, 1.09009893e+02]])

In [93]:
data.T

California         Texas       Florida      New York  Pennsylvania
area     4.239670e+05  6.956620e+05  1.703120e+05  1.412970e+05  1.192800e+05
pop      3.953822e+07  2.914550e+07  2.153819e+07  2.020125e+07  1.300270e+07
density  9.325778e+01  4.189607e+01  1.264631e+02  1.429701e+02  1.090099e+02

In [94]:
data.values[0]

array([4.23967000e+05, 3.95382230e+07, 9.32577842e+01])

In [95]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [96]:
data.iloc[:3,:2]

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [97]:
data.loc[:'Florida',:'pop']

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [98]:
data.loc[data.density>120,['pop','density']]

pop     density
Florida   21538187  126.463121
New York  20201249  142.970120

In [100]:
data.iloc[0,2]=90
data

area       pop     density
California    423967  39538223   90.000000
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

In [101]:
data['Florida':'New York']

area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

In [102]:
data[1:3]

area       pop     density
Texas    695662  29145505   41.896072
Florida  170312  21538187  126.463121

In [103]:
data[data.density>120]

area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

# Pandas에서 데이터연산하기

In [3]:
# 유니버셜 함수 : 인덱스 보존

import pandas as pd
import numpy as np

rng=np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [5]:
df=pd.DataFrame(rng.randint(0,10,(3,4)),
                columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [6]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [7]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [8]:
#유니버설 함수 :인덱스 정렬 

## Series에서 인덱스 정렬

area=pd.Series({'Alaska':1723337, 'Texas':695662,
                'California':423967}, name='area')

population = pd.Series({'California':38332521, 'Texas':26448193,
                        'New York':19651127}, name='population')

In [9]:
population/area   # index를 토대로 element-wise

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [13]:
area.index|population.index

TypeError: unsupported operand type(s) for |: 'str' and 'str'

In [14]:
A=pd.Series([2,4,6],index=[0,1,2])
B=pd.Series([1,3,5],index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [15]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

# DataFrame에서 인덱스 정렬

In [17]:
A=pd.DataFrame(rng.randint(0,20,(2,2)),
               columns=list('AB'))
A

A   B
0   0  11
1  11  16

In [24]:
B=pd.DataFrame(rng.randint(0,10,(3,3)),
               columns=list('ABC'))
B

A  B  C
0  1  7  3
1  1  5  5
2  9  3  5

In [25]:
A+B

A     B   C
0   1.0  18.0 NaN
1  12.0  21.0 NaN
2   NaN   NaN NaN

In [26]:
fill=A.stack().mean()
A.add(B,fill_value=fill)

A     B     C
0   1.0  18.0  12.5
1  12.0  21.0  14.5
2  18.5  12.5  14.5

# 유니버셜 함수 : DataFrame과 Series간의 연산

In [27]:
A=rng.randint(10,size=(3,4))
A

array([[1, 9, 1, 9],
       [3, 7, 6, 8],
       [7, 4, 1, 4]])

In [28]:
A-A[0]

array([[ 0,  0,  0,  0],
       [ 2, -2,  5, -1],
       [ 6, -5,  0, -5]])

In [37]:
df=pd.DataFrame(A,columns=list('QRST'))
df

Q  R  S  T
0  1  9  1  9
1  3  7  6  8
2  7  4  1  4

In [38]:
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  2 -2  5 -1
2  6 -5  0 -5

In [33]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -8  0 -8  0
1 -4  0 -1  1
2  3  0 -3  0

In [34]:
halfrow=df.iloc[0,::2]
halfrow

Q    1
S    1
Name: 0, dtype: int32

In [35]:
df-halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  2.0 NaN  5.0 NaN
2  6.0 NaN  0.0 NaN

# 누락된 데이터 처리하기

In [47]:
vals1=np.array([1,None,2,3])
vals1

array([1, None, 2, 3], dtype=object)

In [43]:
%timeit np.arange(1E6, dtype=int).sum()

1.46 ms ± 100 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [45]:
%timeit np.arange(1E6,dtype=object).sum()

44.7 ms ± 1.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

# Nan : 누락된 숫자 데이터

In [50]:
vals2 =np.array([1,np.nan,3,4])
vals2.dtype

dtype('float64')

In [51]:
1+np.nan

nan

In [52]:
0*np.nan

nan

In [53]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [54]:
np.nansum(vals2),np.nanmin(vals2),np.nanmax(vals2)

(8.0, 1.0, 4.0)

# Pandas에서 Nan과 None

In [55]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [58]:
x=pd.Series(range(2),dtype=int)
x

0    0
1    1
dtype: int32

In [60]:
x[0]=None
x

0    NaN
1    1.0
dtype: float64

In [61]:
pd.Series([1,np.nan,2,None,pd.NA],dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

# Null값 연산하기

In [62]:
# 널값 탐지

data=pd.Series([1,np.nan,'hello',None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [63]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [64]:
# 널값 제거하기

data.dropna()

0        1
2    hello
dtype: object

In [66]:
df=pd.DataFrame([[1,np.nan,2],
                 [2,3,5],
                 [np.nan,4,6]])

df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [67]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [68]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [69]:
df[3]=np.NaN
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [70]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [71]:
df.dropna(axis='rows',thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [73]:
data=pd.Series([1,np.nan,2,None,3],index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [74]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [75]:
data.fillna(method='ffill')

C:\Users\user\AppData\Local\Temp\ipykernel_12076\1844443866.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [76]:
data.fillna(method='bfill')

C:\Users\user\AppData\Local\Temp\ipykernel_12076\1397359497.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [77]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [78]:
df.fillna(method='ffill',axis=1)

C:\Users\user\AppData\Local\Temp\ipykernel_12076\2272395643.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',axis=1)


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# 계층적 인덱싱

In [79]:
index = [('California',2000),('California',2010),
         ('New York',2000),('New York',2010),
         ('Texas',2000),('Texas',2010)]
population = [33871648, 37253956,
              18976457, 19378102,
              20851820, 25145561]
pop = pd.Series(population, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [80]:
pop[('California',2010):('Texas',2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [81]:
pop[[i for i in pop.index if i[1]==2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [82]:
# Pandas MultiIndex

index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [83]:
pop=pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [84]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [85]:
pop_df=pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [86]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [88]:
pop_df=pd.DataFrame({'total':pop,
                     'under18':[9267089,9284094,
                                4687374,4318033,
                                5906301,6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [89]:
f_u18=pop_df['under18']/pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [90]:
df=pd.DataFrame(np.random.rand(4,2),
                index=[['a','b','b','b'],[1,2,1,2]],
                columns=['data1','data2'])
df

data1     data2
a 1  0.048732  0.564343
b 2  0.604783  0.894791
  1  0.909289  0.173773
  2  0.001726  0.172353

In [91]:
data={('California',2000):33871648,
      ('California',2010):37253956,
      ('Texas',2000):20851820,
      ('Texas',2010):25145561,
      ('New York',2000): 18976457,
      ('New York',2010):19378102}

pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [92]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [93]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [94]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [101]:
pd.MultiIndex(levels=[['a','b'],[1,2]],
            labels=[[0,0,1,1],[0,1,0,1]])

TypeError: __new__() got an unexpected keyword argument 'labels'

In [103]:
pop.index.names=['state','year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [136]:
index=pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])

columns=pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],names=['subject','type'])

In [132]:
data=np.round(np.random.randn(4,6),1)
data[:,::2] *=10
data+=37

In [133]:
data

array([[45. , 35.7, 41. , 37. , 43. , 38.5],
       [38. , 36.9, 35. , 37.2, 42. , 38.1],
       [51. , 37. , 40. , 36.7, 39. , 36.7],
       [42. , 36.5, 49. , 37.9, 47. , 36.9]])

In [137]:
health_data = pd.DataFrame(data, index=index, columns=columns)
print(health_data)

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      45.0  35.7  41.0  37.0  43.0  38.5
     2      38.0  36.9  35.0  37.2  42.0  38.1
2014 1      51.0  37.0  40.0  36.7  39.0  36.7
     2      42.0  36.5  49.0  37.9  47.0  36.9


In [138]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      41.0  37.0
     2      35.0  37.2
2014 1      40.0  36.7
     2      49.0  37.9

In [139]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [140]:
pop['California',2000]

33871648

In [141]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [142]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [143]:
pop[:,2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [144]:
pop[pop<22000000]

state     year
New York  2000    18976457
          2010    19378102
Texas     2000    20851820
dtype: int64

In [145]:
pop[['California','Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [146]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      45.0  35.7  41.0  37.0  43.0  38.5
     2      38.0  36.9  35.0  37.2  42.0  38.1
2014 1      51.0  37.0  40.0  36.7  39.0  36.7
     2      42.0  36.5  49.0  37.9  47.0  36.9

In [147]:
health_data['Guido','HR']

year  visit
2013  1        41.0
      2        35.0
2014  1        40.0
      2        49.0
Name: (Guido, HR), dtype: float64

In [148]:
health_data.iloc[:2,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      45.0  35.7
     2      38.0  36.9

In [149]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        45.0
      2        38.0
2014  1        51.0
      2        42.0
Name: (Bob, HR), dtype: float64

In [150]:
health_data.loc[(:,1),(:,'HR')]

SyntaxError: invalid syntax (3480173087.py, line 1)

In [151]:
idx=pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      45.0  41.0  43.0
2014 1      51.0  40.0  39.0

In [152]:
# 정렬된 인덱스와 정렬되지 않은 인덱스


index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data=pd.Series(np.random.rand(6),index=index)
data.index.names=['char','int']

In [153]:
data

char  int
a     1      0.386048
      2      0.335432
c     1      0.984680
      2      0.626484
b     1      0.335821
      2      0.931437
dtype: float64

In [154]:
try : 
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [155]:
data=data.sort_index()
data

char  int
a     1      0.386048
      2      0.335432
b     1      0.335821
      2      0.931437
c     1      0.984680
      2      0.626484
dtype: float64

In [156]:
data['a':'b']

char  int
a     1      0.386048
      2      0.335432
b     1      0.335821
      2      0.931437
dtype: float64

In [157]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [158]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [159]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [160]:
# 인덱스 설정 및 재설정 

pop_flat=pop.reset_index(name='popultion')
pop_flat

state  year  popultion
0  California  2000   33871648
1  California  2010   37253956
2    New York  2000   18976457
3    New York  2010   19378102
4       Texas  2000   20851820
5       Texas  2010   25145561

In [162]:
pop_flat.set_index(['state','year'])

popultion
state      year           
California 2000   33871648
           2010   37253956
New York   2000   18976457
           2010   19378102
Texas      2000   20851820
           2010   25145561

# 데이터세트 결합 : Concat과 Append

In [164]:
def make_df(cols,ind):
    data={c: [str(c)+str(i) for i in ind]
          for c in cols}
    
    return pd.DataFrame(data,ind)

In [165]:
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [167]:
class display(object):
    
    
    def __init__(self,*args):
        self.args=args
    def _repr_html_(self):
        return'\n'.join(self.template.format(a,eval(a)._reper_html())
                        for a in self.args)
    def __reper__(self):
        return '\n\n'.join(a+'\n'+repr(eval(a))
                        for a in self.args)

In [168]:
x=[1,2,3]
y=[4,5,6]
z=[7,8,9]

np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
x=[[1,2],
   [3,4]]

np.concatenate([x,x],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [171]:
# pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
#           keys=None, levels=None, names=None, verify_integrity=False,
#           copy=True)

In [175]:
ser1 = pd.Series(['A','B','C'],index=[1,2,3])
ser2 = pd.Series(['D','E','F'],index=[4,5,6])

In [176]:
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [177]:
df1=make_df('AB',[1,2])
df2=make_df('AB',[3,4])

In [178]:
print(df1)
print(df2)
print(pd.concat([df1,df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [179]:
df3=make_df('AB',[0,1])
df4=make_df('CD',[0,1])
print(df3)
print(df4)
print(pd.concat([df3,df4],axis=1))


    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [181]:
x=make_df('AB',[0,1])
y=make_df('AB',[2,3])
y.index=x.index
print(x)
print(y)
print(pd.concat([x,y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [182]:
try : 
    pd.concat([x,y], verify_integrity=True)
except ValueError as e :
    print("ValueError:",e)

ValueError: Indexes have overlapping values: Index([0, 1], dtype='int64')


In [183]:
print(x)
print(y)
print(pd.concat([x,y], ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [184]:
print(x)
print(y)
print(pd.concat([x,y],keys=['x','y']))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3


In [185]:
df5=make_df('ABC',[1,2])
df6=make_df('BCD',[3,4])
print(df5)
print(df6)
print(pd.concat([df5,df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


In [186]:
print(df5)
print(df6)
print(pd.concat([df5,df6], join='inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4
